deprecate and remove namespace_fixup.sh

diff --git a/startup/rfhs-container-init b/startup/rfhs-container-init
--- a/startup/rfhs-container-init
+++ b/startup/rfhs-container-init
@@ -7,6 +7,25 @@ if [ -n "${DEBUG}" ]; then
 	set -x
 fi
 
+create_ns_link() {
+  # Set the name for the namespace
+  PID="$(docker inspect -f '{{.State.Pid}}' "${CONTAINER_NAME}")"
+  if [ -z "${PID}" ]; then
+    printf "Unable to identify process id for %s, skipping.\n" "${CONTAINER_NAME}"
+    exit 1
+  fi
+  mkdir -p /run/netns/
+  if mountpoint -q -- "/run/netns/${CONTAINER_NAME}"; then
+    # Remove the stale namespace mounting
+	  printf "Stale namespace found at /run/netns/%s\n" "${CONTAINER_NAME}"
+  	printf "Removing stale namespace\n"
+  	ip netns delete "${CONTAINER_NAME}"
+  fi
+  touch "/run/netns/${CONTAINER_NAME}"
+  printf "Mapping namespaces of process id %s for %s to namespace name %s\n" "${PID}" "${CONTAINER_NAME}" "${CONTAINER_NAME}"
+  mount -o bind "/proc/${PID}/ns/net" "/run/netns/${CONTAINER_NAME}"
+}
+
 # shellcheck disable=SC2153
 for CONTAINER_NETWORK in ${CONTAINER_NETWORKS}; do
   if [ -z "$(docker network ls  --filter name="${CONTAINER_NETWORK}" --format '{{ .ID }}')" ]; then
@@ -21,12 +40,6 @@ done
 if [ -n "$(docker ps --filter name="${CONTAINER_NAME}" --format '{{ .ID }}' )" ]; then
 	echo "Found existing ${CONTAINER_NAME} container... QUITTING"
 	exit 1
-fi
-
-if [ -f "/run/netns/${CONTAINER_NAME}" ]; then
-	echo "Stale namespace found at /run/netns/${CONTAINER_NAME}"
-	echo "Removing stale namespace"
-	ip netns delete "${CONTAINER_NAME}"
 fi
 
 if [ -n "${CONTAINER_PHYS}" ]; then
@@ -73,6 +86,7 @@ else
       -v "/var/log/rfhs-rfctf/${CONTAINER_NAME}":/var/log \
       "${CONTAINER_IMAGE}"
       #--privileged --userns host \
+      # XXX need to do bridge aging outside the container to not require privileged
 
     docker network connect openwrt-eth1 "${CONTAINER_NAME}"
 
@@ -106,10 +120,11 @@ else
   fi
 fi
 
-"$(dirname "${0}")"/namespace_fixup.sh "${CONTAINER_NAME}"
+# Set the name for the namespace
+create_ns_link
 
 if [ -n "${CONTAINER_PHYS}" ]; then
-  clientpid=$(docker inspect --format "{{ .State.Pid }}" "${CONTAINER_NAME}")
+  #clientpid=$(docker inspect --format "{{ .State.Pid }}" "${CONTAINER_NAME}")
   for phy_num in ${CONTAINER_PHYS}; do
     while true; do
       if iw phy "phy${phy_num}" info > /dev/null 2>&1; then
@@ -119,7 +134,7 @@ if [ -n "${CONTAINER_PHYS}" ]; then
       printf "Unable to find phy%s, waiting...\n" "${phy_num}"
       sleep 1
     done
-    iw phy "phy${phy_num}" set netns "${clientpid}"
-    #iw phy "phy${phy_num}" set netns name "${CONTAINER_NAME}"
+    #iw phy "phy${phy_num}" set netns "${clientpid}"
+    iw phy "phy${phy_num}" set netns name "${CONTAINER_NAME}"
   done
 fi
