add in some safety checks, that probably work

diff --git a/startup/rfhs-container-init b/startup/rfhs-container-init
--- a/startup/rfhs-container-init
+++ b/startup/rfhs-container-init
@@ -7,6 +7,8 @@ if [ -n "${DEBUG}" ]; then
 	set -x
 fi
 
+source "$(dirname "${0}")"/rfhs-helpers.sh
+
 create_ns_link() {
   # Set the name for the namespace
   PID="$(docker inspect -f '{{.State.Pid}}' "${CONTAINER_NAME}")"
@@ -138,21 +140,19 @@ fi
 create_ns_link
 
 if [ -n "${CONTAINER_PHYS}" ]; then
-  #clientpid=$(docker inspect --format "{{ .State.Pid }}" "${CONTAINER_NAME}")
   for phy_num in ${CONTAINER_PHYS}; do
     while true; do
       if iw phy "phy${phy_num}" info > /dev/null 2>&1; then
-        # This commented code would protect users from accidently pulling their physical wifi cards
-        # into the virtual game environment.  Unfortunately it also breaks the ability to run a physical game.
-        #unset driver
-        #driver="$(awk -F'=' '{print $2}' "/sys/class/ieee80211/phy${phy_num}/device/uevent")"
-        #if [ 'mac80211_hwsim' = "${driver}" ]; then
-          printf "Found phy%s, moving it into %s\n" "${phy_num}" "${CONTAINER_NAME}"
-          break
-        #else
-        #  printf "Requested phy is using %s driver instead of the expected mac80211_hwsim.  Failing safe.\n" "${driver}"
-        #  exit 1
-        #fi
+        if ! is_vm; then
+          unset driver
+          driver="$(awk -F'=' '{print $2}' "/sys/class/ieee80211/phy${phy_num}/device/uevent")"
+          if [ 'mac80211_hwsim' != "${driver}" ]; then
+            printf "Requested phy is using %s driver instead of the expected mac80211_hwsim.  Failing safe.\n" "${driver}"
+            exit 1
+          fi
+        fi
+        printf "Found phy%s, moving it into %s\n" "${phy_num}" "${CONTAINER_NAME}"
+        break
       fi
       printf "Unable to find phy%s, waiting...\n" "${phy_num}"
       sleep 1
